### ISSUE TITLE
Time-boxed spike research on "ethereum-etl"

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-graph#166]
https://github.com/blockchain-etl/ethereum-etl

This is the link for a popular lib to index ethereum data. I want to propose to have a 4 hours time-boxed spike to get to know, learn about this lib and try to set it up. After the ticket we talk about the learning of it. And I’m think probably @markdavison can take on this effort.

Suggestions are welcome.

**Comment by markdavison** [comment]
Looks interesting. I will take a look.

**Comment by markdavison** [comment]
### Findings

**Overview**
The tool indexes all blocks, contracts, logs, receipts, transactions and traces (internal transactions) and can store them in a number of different formats (including CSV and postgres).

To test it out I span an instance of it up in docker on my machine and indexed two days into CSV format. They are quite large - so I can not upload them here... but if anyone is interested I can send them to you.

**Performance**
With a single thread on my laptop it took roughly an hour per day indexed. The readme states you can do all of the chains history in [two hours using AWS data pipeline and autoscaling ](https://medium.com/coinmonks/how-to-export-the-entire-ethereum-blockchain-to-csv-in-2-hours-for-10-69fef511e9a2). I am not sure that we can compare much on the performance given how different the approaches are.

**Limitations**
Some interesting limitations detailed that will impact us in the moonbeam work:

- In case the contract is a proxy, which forwards all calls to a delegate, interface detection doesn’t work, which means is_erc20 and is_erc721 will always be false for proxy contracts and they will be missing in the tokens table.

- The metadata methods (symbol, name, decimals, total_supply) for ERC20 are optional, so around 10% of the contracts are missing this data. Also some contracts (EOS) implement these methods but with wrong return type, so the metadata columns are missing in this case as well.

**Errors**
While indexing the two days I did get quite a lot of errors in the output - `evmdasm.disassembler [ERROR] - invalid instruction: PUSH9` with various different variations of  'PUSH(\d+)'. Presumably this is where it is trying to disassemble a contract... so maybe the issue is with the contracts rather then the tool?

**Summary**
It looks like a useful tool, I am not yet sure where we would use it, but if we find that there is some data that we can not get with out existing tooling then I see no issues with us integrating this into Litentry graph. We could have it export to postgres and add a graphql interface to the data.

The investigation was useful (and fortunate timing) as it helped impact the direction of the moonbeam contract identification - mostly it reinforced the approach we had planned... but it did lead us to a helpful node library.

**Comment by geastwood** [comment]
FYI: @wangminqi @Moehringen @trmaphi

**Comment by geastwood** [comment]
@markdavison very good finding, and thank you for the effort. ❤️
